version: '3.8'

services:
  web:
    build: .
    container_name: be_ai_django
    restart: always
    ports:
      - "80:8000"
    volumes:
      - static_volume:/app/staticfiles
    command: >
     sh -c  "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn AI_service.wsgi:application --bind 0.0.0.0:8000"
    env_file:
        - ./.env
    dns:
      - 8.8.8.8

volumes:
  static_volume: